### PR TITLE
[WIP]added the latest .whl files for the license_expression(Part of the issue:adding License Expression to DeltaCode)

### PR DESCRIPTION
**Pull request by pratik0316**
In this PR I changed the thirdparty packages by inserting new .whl packages for license_expression(version:1.2,old version 0.99)

### CODE REVIEW

**Comment by pratik0316** [comment]
@majurg this PR is meant to update the TPP to have the latest license_expression library.Regarding the integration of this library I have a few queries:
I was testing the functionalities of license_expression
It had the options to :
`is_equivalent` : for testing two expressions
`parse`:for parsing a library exp
`contains`:for checking weather an exp is contained in another
and many more
But in DeltaCode currently we are currently dealing with mainly files(and its status), if any license is present in a file it takes the additional info from it (like owner, category) in a string expression for each deltas.
So for what purpose(s), can we eventually make use of this library?

**Comment by steven-esser** [comment]
@Pratikrocks the license_expression library has the ability to `simplify()` a complex expression down to its base license_key (and category) elements. 

Since we are only using string comparison on license_expression values ATM, we will want to be able to compare complex expressions and their categories and score them appropriately. 

For example, currently when we compare `mit OR bsd-new OR mit` with `mit OR bsd-new`, this would fail currently. With the license expression library, we would be able to compare these correctly.

**Comment by pratik0316** [comment]
Okay so basically we are going to deal here with deltas having multiple licenses and going to tokenize it down.

**Comment by steven-esser** [comment]
yes

**Comment by steven-esser** [comment]
Closing due to stagnation.

**Pull request closed without merging**
