### PR TITLE
Added readthedocs support for deltacode

### PR DESCRIPTION
**Pull request by ankit2001**
This pr is meant to solve issue #133 . I have moved the deltacode documentation to readthedocs ,now you can configure deltacode repo to deltacode.readthedocs.io.
Please review it @majurg 
Screenshot from 2020-03-14 23-13-01

### CODE REVIEW

**Comment by ankit2001** [comment]
i have also #138 pr opened , please review both the pr @majurg  and suggest me changes.

**Comment by ankit2001** [comment]
I also have #138 pr opened , please review both the pr @majurg and sugest me changes

**Review by steven-esser — CHANGES_REQUESTED** [review]
@ankit2001 Before I can continue to review this, you need to address the following items:

1) remove everything related to the docs virtualenv from this PR
2) remove everything from the docs build directory from this PR

It seems like you have those added to the .gitignore file, but they are included in this PR for some and it is impossible to review at the moment. 

Also, please rebase this branch into a single commit. Commit mesages such as "Updates" or "changes" are not helpful. It is much better to rebase into a single commit that has descriptive commit message

**Comment by ankit2001** [comment]
i have done the changes now u can review it @majurg , i also added license.rst page ,if you do not need it , i can remove it.

**Review by steven-esser — COMMENTED** [review]
@ankit2001 Was the config + content take from the aboutcode repo? Just making sure here.

**Comment by ankit2001** [comment]
Yeah @majurg  , just added license page also, i thought we need it , i can remove it  if you want.

**Review by steven-esser — CHANGES_REQUESTED** [review]
Please remove the license.rst file

**Comment by steven-esser** [comment]
Closing due to stagnation.

**Pull request closed without merging**
