### PR TITLE
Added has_license and has_copyright to delta object

### LINKED ISSUE #109: Add has_license and has_copyright flags to Delta object
Related to #107. 

As we move away from factors, these two flags are needed for better consumption of results.

We should add these to our Delta objects and make sure they function appropriately.

### PR DESCRIPTION
**Pull request by shubhscoder**
Fixes #109 
Signed-off-by: Shubham <shubhamsangamnerkar9@gmail.com>

### CODE REVIEW

**Comment by shubhscoder** [comment]
@majurg , this is my first Pull request, please suggest me any required changes. Thank you !

**Review by steven-esser — CHANGES_REQUESTED** [review]
@shubhscoder This is the correct first start. However, we want to populate these new field values properly in the right places. 

See the various license and copyright functions in https://github.com/nexB/deltacode/blob/develop/src/deltacode/utils.py

Where we run `delta.update(blah blah)` we will want update these new flags for our Delta object and remove the "factors" that are added at each of these conditions.

**Comment by shubhscoder** [comment]
@majurg , I have tried updating has_license and has copyright. The remaining delta.update would I guess go with addition of status right ? Also I know why the tests are failing because we have removed the scoring system. Should I try updating and addition of "status" in this PR itself? Then probably I can try updating the tells together. Also I am not sure why DCO is failing. The expected and received signs are exactly same. 
Thank you so much !

**Comment by pombredanne** [comment]
Nit: please use an imperative style and not the past tense for your commit title. Also suffix it with the ticket number. And then explain in the body what this commit does
e.g. not `Added has_license and has_copyright to delta object`
but rather  `Add has_license/has_copyright to delta object #109` 

See https://github.com/nexB/aboutcode/wiki/Writing-good-commit-messages

**Comment by pombredanne** [comment]
also your git user config should match your signoff for the DCO bot to be happy ;)

**Comment by shubhscoder** [comment]
> Nit: please use an imperative style and not the past tense for your commit title. Also suffix it with the ticket number. And then explain in the body what this commit does
> e.g. not `Added has_license and has_copyright to delta object`
> but rather `Add has_license/has_copyright to delta object #109`
> 
> See https://github.com/nexB/aboutcode/wiki/Writing-good-commit-messages

Thank you so much! I updated the commit message.

**Comment by shubhscoder** [comment]
> also your git user config should match your signoff for the DCO bot to be happy ;)

@pombredanne , the "expected" and the "got" fields are exactly same. Also I checked with my local git, the global configuration is same as the signoff. 
fix

Thank you!

**Comment by pombredanne** [comment]
@shubhscoder the DCO bot may have a bug ... but in any case you need to sign with your full name. Thank you for fixing this

**Comment by shubhscoder** [comment]
Okay I ll do that. Thank you!

**Comment by steven-esser** [comment]
Closing due to stagnation.

**Pull request closed without merging**
