### PR TITLE
Added the azure pipelines for the ubuntu-16.04,18,04 and macOS-10.14,10.15

### PR DESCRIPTION
**Pull request by pratik0316**
In this PR I have added the azure Pipelines for the macOS and linux builds

### CODE REVIEW

**Review by steven-esser — CHANGES_REQUESTED** [review]
Have you tested this?

**Comment by pratik0316** [comment]
Yes @majurg I have tested it ,they are working

**Comment by steven-esser** [comment]
PLease link a log

**Comment by pratik0316** [comment]
Sure

**Comment by pratik0316** [comment]
@majurg  the link to the logs [azure](https://dev.azure.com/pratikrocksdey11/Demo/_build/results?buildId=55&view=results)

**Comment by Pratikrocks** [comment]
@majurg, @pombredanne  sir , can you please enable the azure pipelines for this repository , if no further changes are required

**Comment by pratik0316** [comment]
@majurg , sorry the previous links to the logs are showing unauthorized error for other users, I was not sure of that before,I just recently noticed it. Please view this [logs](https://drive.google.com/drive/folders/1_YqcjwWsw_sBb6fiv3kSk5xVGSSm2JWP?usp=sharing) for all the builds

**Comment by steven-esser** [comment]
Holding off on this for now, as the azure free tests are currently suspended due to covid19

**Comment by pratik0316** [comment]
@majurg  , sure no issues with it .

**Comment by steven-esser** [comment]
#162 handles this. Closing.

**Pull request closed without merging**
