### PR TITLE
Added the scaned options for the old and the new files

### PR DESCRIPTION
**Pull request by pratik0316**
In this PR I have added a method to add the scanned options in the new and old file, These options will be available shown in the json file of the deltacode json file output.
The new json file will now contain an additional field of `scanned_options` in it.
Screenshot from 2020-03-19 11-01-28
So this is my new json file output containing the scanned options present in the new and old file scans
This PR is addressed to the issue of #2

### CODE REVIEW

**Comment by pratik0316** [comment]
@majurg I have inserted scanned options for new and old file in the deltacode output ,I have not modified the test case so due to this some of the test cases(3 test cases in both windows and osx build ) are not successful as the expected and the actual results in the output are different to some extent(regarding the output in the json file) .Sir if you would kindly review this PR and suggest changes, I would be modifying the test cases too.

**Review by steven-esser — CHANGES_REQUESTED** [review]
Is this related to a ticket at all? I am not sure we want this...

**Comment by pratik0316** [comment]
Thanks sir for the review.
Sir I think the issue of #2 is related to it.

**Comment by pratik0316** [comment]
In this Pr my two cases are failing in both Linux and osx build out of 155 test cases

**Comment by steven-esser** [comment]
@Pratikrocks You will need to regen those two particular test files since you have added some additional output

**Comment by pratik0316** [comment]
okay @majurg I am trying to sort it out

**Comment by pratik0316** [comment]
Actually the error is generated due to mismatch in the in the result file
`expected_file = '/home/travis/build/nexB/deltacode/tests/data/deltacode/sugar-expected.json'
result_file = '/home/travis/build/nexB/deltacode/lib/python2.7/tmp/scancode-tk-tests -29D3x6/1j9Ryh/td/tf.json'`
This file is generated in the server side during its configuration(as it is present in the lib directory).
How can we change this file

**Comment by steven-esser** [comment]
The test files on Travis are taken from the ones in the codebase.

**Comment by steven-esser** [comment]
Closing due to stagnation.

**Pull request closed without merging**
