### PR TITLE
Add package url support for deltacode

### PR DESCRIPTION
**Pull request by ankit2001**

### CODE REVIEW

**Comment by ankit2001** [comment]
hey, @majurg , i am adding package-url-support for deltacode so that we can further do differing on based of packages, can you please review and suggest me changes .
Screenshot from 2020-03-18 14-46-47

**Comment by ankit2001** [comment]
i have used the refrence https://github.com/package-url/packageurl-python

**Review by steven-esser — CHANGES_REQUESTED** [review]
This is not how we want to add the packageurl library. We want to simply add the `.whl` file to the `thirdparty/` directory.

**Comment by ankit2001** [comment]
Sorry for misleading @majurg  , i will add it in new pr

**Comment by ankit2001** [comment]
i am closing this now.

**Pull request closed without merging**
