### PR TITLE
Fix all broken tests and minor refactoring

### PR DESCRIPTION
**Pull request by arnav-mandal1234**
Fixes all the broken tests. All the test cases are passing now.

### CODE REVIEW

**Review by AyanSinhaMahapatra — APPROVED** [review]
Thanks! This looks good to me.

The failing tests are for two things IMHO:

- ubuntu_16/macos10_14/win_2016 is not supported anymore in azure piplines/github actions, so you get the `The remote provider was unable to process the request` errors
- all `python 3.6` jobs are failing, probably due to some issue of python3.6 not being supported anymore.

This should go away after we merge skeleton into deltacode #182  as the [azure-pipelines.yml](https://github.com/nexB/skeleton/blob/main/azure-pipelines.yml) is updated there with latest images and python versions.

We probably only want to support python 3.8+ as python 3.7 will also be deprecated soon, in ~3 months. Anyway we are merging deltacode in scancode-toolkit #183  so this isn't that important.

LGTM!

**Comment by AyanSinhaMahapatra** [comment]
@pombredanne ready for your review!

**Review by pombredanne — APPROVED** [review]
LGTM!
I assume that the failing tests on the CI are because the skeleton is merged in another PR.

**Comment by arnav-mandal1234** [comment]
@pombredanne yes, will update the skeleton in another PR.

**Pull request merged**
